server:
  port: 8080
spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://192.168.218.134:3306/cloud?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      config:
        server-addr: 192.168.218.134:8848
        #        import-check:
        #          enabled: false
        #        group: DEFAULT_GROUP
        file-extension: yaml
      #        namespace: public
      discovery:
        cluster-name: HZ # 集群名称
        server-addr: 192.168.218.134:8848
feign:
  client:
    config:
      default: # default全局的配置
#        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
mybatis:
  type-aliases-package: cn.onenewcode.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS